name: OpenSpec Badge
description: Generate SVG badges showing OpenSpec metrics for your repository

branding:
  icon: award
  color: green

inputs:
  metric_types:
    description: >
      Comma-separated list of metrics to display.
      Supported: number_of_specs, number_of_requirements, tasks_status, open_changes
    required: false
    default: 'number_of_specs,number_of_requirements,tasks_status,open_changes'
  badge_style:
    description: 'Badge visual style: classic (gradient) or flat (solid)'
    required: false
    default: 'classic'
  show_label:
    description: 'Show "OpenSpec" text label in badge (true/false)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    # --- 1. Input validation ---
    - name: Validate inputs
      id: validate
      shell: bash
      run: |
        SUPPORTED_METRICS="number_of_specs number_of_requirements tasks_status open_changes"
        IFS=',' read -ra METRICS <<< "${{ inputs.metric_types }}"
        for metric in "${METRICS[@]}"; do
          metric=$(echo "$metric" | xargs)  # trim whitespace
          if ! echo "$SUPPORTED_METRICS" | grep -qw "$metric"; then
            echo "::error::Invalid metric type: '$metric'. Supported: $SUPPORTED_METRICS"
            exit 1
          fi
        done

        STYLE="${{ inputs.badge_style }}"
        if [[ "$STYLE" != "classic" && "$STYLE" != "flat" ]]; then
          echo "::error::Invalid badge_style: '$STYLE'. Supported: classic, flat"
          exit 1
        fi

        SHOW_LABEL="${{ inputs.show_label }}"
        # Convert to boolean: accept 'true', 'TRUE', '1' as true, everything else as false
        if [[ "$SHOW_LABEL" =~ ^(true|TRUE|1)$ ]]; then
          SHOW_LABEL="true"
        else
          SHOW_LABEL="false"
        fi

        echo "metrics=${METRICS[*]}" >> $GITHUB_OUTPUT
        echo "style=$STYLE" >> $GITHUB_OUTPUT
        echo "show_label=$SHOW_LABEL" >> $GITHUB_OUTPUT

    # --- 2. OpenSpec CLI setup ---
    - name: Install OpenSpec CLI
      shell: bash
      run: |
        if ! command -v openspec &> /dev/null; then
          echo "Installing OpenSpec CLI..."
          npm install -g @fission-ai/openspec
        else
          echo "OpenSpec CLI already available: $(openspec --version)"
        fi

    - name: Verify OpenSpec project
      shell: bash
      run: |
        if [ ! -f "openspec/config.yaml" ]; then
          echo "::error::No openspec/config.yaml found. This repository is not an OpenSpec project."
          exit 1
        fi

    # --- 3. Metrics collection ---
    - name: Collect spec metrics
      id: specs
      shell: bash
      run: |
        SPECS_JSON=$(openspec spec list --json 2>/dev/null || echo "[]")
        SPEC_COUNT=$(echo "$SPECS_JSON" | node -p 'JSON.parse(require("fs").readFileSync(0,"utf8")).length')
        REQ_COUNT=$(echo "$SPECS_JSON" | node -p 'JSON.parse(require("fs").readFileSync(0,"utf8")).reduce((s,x)=>s+(x.requirementCount||0),0)')
        echo "spec_count=$SPEC_COUNT" >> $GITHUB_OUTPUT
        echo "req_count=$REQ_COUNT" >> $GITHUB_OUTPUT

    - name: Collect change metrics
      id: changes
      shell: bash
      run: |
        CHANGES_JSON=$(openspec list --changes --json 2>/dev/null | node -p 'JSON.stringify(JSON.parse(require("fs").readFileSync(0,"utf8")).changes || [])')
        OPEN_CHANGES=$(echo "$CHANGES_JSON" | node -p 'JSON.parse(require("fs").readFileSync(0,"utf8")).length')
        COMPLETED_TASKS=$(echo "$CHANGES_JSON" | node -p 'JSON.parse(require("fs").readFileSync(0,"utf8")).reduce((s,x)=>s+(x.completedTasks||0),0)')
        TOTAL_TASKS=$(echo "$CHANGES_JSON" | node -p 'JSON.parse(require("fs").readFileSync(0,"utf8")).reduce((s,x)=>s+(x.totalTasks||0),0)')
        echo "open_changes=$OPEN_CHANGES" >> $GITHUB_OUTPUT
        echo "completed_tasks=$COMPLETED_TASKS" >> $GITHUB_OUTPUT
        echo "total_tasks=$TOTAL_TASKS" >> $GITHUB_OUTPUT

    # --- 4. Badge generation ---
    - name: Install badgen
      shell: bash
      run: npm install --prefix "$RUNNER_TEMP" badgen

    - name: Generate badges
      id: badges
      shell: bash
      env:
        NODE_PATH: ${{ runner.temp }}/node_modules
        SPEC_COUNT: ${{ steps.specs.outputs.spec_count }}
        REQ_COUNT: ${{ steps.specs.outputs.req_count }}
        OPEN_CHANGES: ${{ steps.changes.outputs.open_changes }}
        COMPLETED_TASKS: ${{ steps.changes.outputs.completed_tasks }}
        TOTAL_TASKS: ${{ steps.changes.outputs.total_tasks }}
        BADGE_STYLE: ${{ steps.validate.outputs.style }}
        METRICS: ${{ steps.validate.outputs.metrics }}
        SHOW_LABEL: ${{ steps.validate.outputs.show_label }}
      run: |
        mkdir -p "$RUNNER_TEMP/badges"

        # Generate badges using the badgen library directly (badgen-cli
        # doesn't pass custom icon data URIs through to the library).
        node -e '
          const { badgen } = require("badgen");
          const fs = require("fs");
          const path = require("path");

          const iconSvg = `<svg width="20" height="20" viewBox="0 0 120 140" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M40 0C53.2 0 66.4 0 80 0C80 6.6 80 13.2 80 20C66.8 20 53.6 20 40 20C40 13.4 40 6.8 40 0Z" fill="#fff"/><path d="M20 20C26.6 20 33.2 20 40 20C40 26.6 40 33.2 40 40C33.4 40 26.8 40 20 40C20 33.4 20 26.8 20 20Z" fill="#fff"/><path d="M80 20C86.6 20 93.2 20 100 20C100 26.6 100 33.2 100 40C93.4 40 86.8 40 80 40C80 33.4 80 26.8 80 20Z" fill="#fff"/><path d="M0 40C6.6 40 13.2 40 20 40C20 59.8 20 79.6 20 100C13.4 100 6.8 100 0 100C0 80.2 0 60.4 0 40Z" fill="#fff"/><path d="M40 40C53.2 40 66.4 40 80 40C80 59.8 80 79.6 80 100C66.8 100 53.6 100 40 100C40 80.2 40 60.4 40 40Z" fill="#fff"/><path d="M100 40C106.6 40 113.2 40 120 40C120 59.8 120 79.6 120 100C113.4 100 106.8 100 100 100C100 80.2 100 60.4 100 40Z" fill="#fff"/><path d="M20 100C26.6 100 33.2 100 40 100C40 106.6 40 113.2 40 120C33.4 120 26.8 120 20 120C20 113.4 20 106.8 20 100Z" fill="#fff"/><path d="M80 100C86.6 100 93.2 100 100 100C100 106.6 100 113.2 100 120C93.4 120 86.8 120 80 120C80 113.4 80 106.8 80 100Z" fill="#fff"/><path d="M40 120C53.2 120 66.4 120 80 120C80 126.6 80 133.2 80 140C66.8 140 53.6 140 40 140C40 133.4 40 126.8 40 120Z" fill="#fff"/></svg>`;
          const iconUri = "data:image/svg+xml;base64," + Buffer.from(iconSvg).toString("base64");

          const specCount = parseInt(process.env.SPEC_COUNT) || 0;
          const reqCount = parseInt(process.env.REQ_COUNT) || 0;
          const openChanges = parseInt(process.env.OPEN_CHANGES) || 0;
          const completedTasks = parseInt(process.env.COMPLETED_TASKS) || 0;
          const totalTasks = parseInt(process.env.TOTAL_TASKS) || 0;
          const isFlat = process.env.BADGE_STYLE === "flat";
          const showLabel = process.env.SHOW_LABEL === "true";
          const metrics = process.env.METRICS.split(" ");
          const outDir = process.env.RUNNER_TEMP + "/badges";

          const metricDefs = {
            number_of_specs: {
              status: specCount + " specs",
              color: specCount > 0 ? "green" : "orange"
            },
            number_of_requirements: {
              status: reqCount + " reqs",
              color: reqCount > 0 ? "green" : "orange"
            },
            tasks_status: {
              status: completedTasks + "/" + totalTasks + " tasks",
              color: totalTasks === 0 ? "blue" : completedTasks === totalTasks ? "green" : completedTasks > 0 ? "orange" : "red"
            },
            open_changes: {
              status: openChanges + " changes",
              color: "blue"
            }
          };

          for (const metric of metrics) {
            const def = metricDefs[metric];
            const svg = badgen({
              subject: showLabel ? "OpenSpec" : "",
              status: def.status,
              color: def.color,
              style: isFlat ? "flat" : "classic",
              icon: iconUri,
              iconWidth: 18
            });
            const outFile = path.join(outDir, metric + ".svg");
            fs.writeFileSync(outFile, svg);
            console.log("Generated: " + metric + " -> " + def.status + " (" + def.color + ")");
          }
        '

    # --- 5. Badge deployment ---
    - name: Configure git user
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Deploy badges
      shell: bash
      env:
        RETRY_LIMIT: "3"
        REF_NAME: ${{ github.ref_name }}
      run: |
        # Ensure clean working tree before branch operations
        git stash --include-untracked 2>/dev/null || true

        # Create gh-pages branch if it doesn't exist on the remote
        if ! git ls-remote --exit-code --heads origin gh-pages > /dev/null 2>&1; then
          echo "Creating orphan gh-pages branch..."
          git checkout --orphan gh-pages
          git rm -rf . 2>/dev/null || true
          git commit --allow-empty -m "Initial commit for badges"
          git push -u origin gh-pages
        fi

        for attempt in $(seq 1 $RETRY_LIMIT); do
          echo "Deploy attempt $attempt/$RETRY_LIMIT"

          git fetch origin gh-pages
          git checkout -f gh-pages
          git reset --hard origin/gh-pages

          mkdir -p badges
          cp "$RUNNER_TEMP/badges/"*.svg badges/

          git add badges/
          if git diff --cached --quiet; then
            echo "No badge changes to commit"
            break
          fi

          git commit -m "Update OpenSpec badges [skip ci]"
          if git push origin gh-pages; then
            echo "Badges deployed successfully"
            break
          fi

          echo "Push failed, retrying..."
          sleep 2
        done

        # Checkout back to the original ref
        git checkout -f "$REF_NAME"
        git stash pop 2>/dev/null || true
